---
# author: lework

- set_fact: mysql57_file_path={{ software_files_path }}/{{ mysql57_bin_file }}
  when: not mysql57_install_from_source
 
- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: service.yml
- import_tasks: replication.yml
  when: mysql57_replication_role != '' and mysql57_replication_channel == {}
- import_tasks: replication_channel.yml
  when: mysql57_replication_channel and mysql57_replication_role == 'slave'
- import_tasks: replication_ga.yml
  when: mysql57_replication_ga and mysql57_replication_mode == 'gtid'
