---
# author: lework

#- name: configure | Set hostname.
#  hostname: "name='{{ zabbix_server_hostanme }}'"

- block:
  - name: configure | Create zabbix logs path.
    file: name={{ zabbix_server_logs_path }} state=directory owner={{ zabbix_server_user }} group={{ zabbix_server_group }}

  - name: configure | Set zabbix pid file.
    replace: path={{ zabbix_server_conf_path }}/{{ item }}.conf regexp='# PidFile=/tmp/{{ item }}.pid' replace=PidFile={{ zabbix_server_logs_path }}/{{ item }}.pid
    with_items:
     - zabbix_server
     - zabbix_agentd

  - name: configure | Set zabbix log file.
    replace: path={{ zabbix_server_conf_path }}/{{ item }}.conf regexp=/tmp replace={{ zabbix_server_logs_path }}
    with_items:
     - zabbix_server
     - zabbix_agentd

  - name: configure | Create zabbix server mysql from source install.
    shell: "source /etc/profile;cat {{ zabbix_server_source_dir }}/database/mysql/{{ item }} | mysql -u{{ zabbix_server_db_user }} -p{{ zabbix_server_db_password }} -h{{ zabbix_server_db_host }} -P{{ zabbix_server_db_port }} {{ zabbix_server_db }}"
    with_items:
     - "schema.sql"
     - "images.sql"
     - "data.sql"
  - name: configure | Set zabbix configuration file in httpd.
    template:
      src: zabbix.conf
      dest: "/etc/httpd/conf.d/zabbix.conf"

  when: zabbix_server_install_from_source
 
- name: configure | Create zabbix server mysql from package install.
  shell: "source /etc/profile;zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -u{{ zabbix_server_db_user }} -p{{ zabbix_server_db_password }} -h{{ zabbix_server_db_host }} -P{{ zabbix_server_db_port }} {{ zabbix_server_db }}"
  when: not zabbix_server_install_from_source
   
- name: configure | Setup zabbix server config file.
  replace: path={{ zabbix_server_conf_path }}/zabbix_server.conf regexp={{ item.r }} replace={{ item.s }}
  with_items:
   - { r: "DBName=zabbix", s: "DBName={{ zabbix_server_db }}"}
   - { r: "DBUser=zabbix", s: "DBUser={{ zabbix_server_db_user }}"}
   - { r: "# DBPassword=", s: "DBPassword={{ zabbix_server_db_password }}"}
   - { r: "# DBHost=localhost", s: "DBHost={{ zabbix_server_db_host }}"}
   
- name: configure | Configure zabbix time zone.
  replace:
    path: /etc/httpd/conf.d/zabbix.conf
    regexp: "# php_value date.timezone Europe/Riga"
    replace: "php_value date.timezone Asia/Shanghai"
  when: not zabbix_server_install_from_source

- name: configure | Ensure zabbix services is started and enabled on boot.
  service: "name={{ item }} state=restarted enabled=yes"
  with_items:
   - zabbix-server
   - zabbix-agent

- name: configure | Restart web services.
  service: "name={{ zabbix_server_webserver }} state=restarted"
