---
# author: lework

- name: install | Ensure mysql packages are installed (RedHat).
  package: "name={{ item }} state=installed"
  with_items:
    - MySQL-python
    - mysql
    - mysql-devel

- import_tasks: install-from-package.yml
  when: not zabbix_server_install_from_source

- import_tasks: install-from-source.yml
  when: zabbix_server_install_from_source
