{% raw %}
#apiVersion: v1
#kind: Secret
#metadata:
#  name: scope-basic-auth
#  namespace: weave
#data:
#  auth: {{auth}}
#type: Opaque

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: scope
  namespace: weave
  annotations:
    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/auth-type: basic
#    nginx.ingress.kubernetes.io/auth-secret: scope-basic-auth
#    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - scope'
spec:
  rules:
  - host: scope.weave.k8s.local
    http:
      paths:
      - backend:
          serviceName: weave-scope-app
          servicePort: 80

{% endraw %}
