apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: ingress-traefik
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: ingress-traefik
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  namespace: ingress-traefik
spec:
  type: LoadBalancer
  externalIPs:
    - "{{ kubernetes_apiserver_vip }}"
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 8580
      name: admin
  selector:
    k8s-app: traefik-ingress
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress
  labels:
    k8s-app: traefik-ingress
    addonmanager.kubernetes.io/mode: Reconcile
  namespace: ingress-traefik
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - name: traefik-ingress-lb
        image: {{ kubernetes_traefik_ingress_controller_image }}
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8580
          hostPort: 8580
        securityContext:
          privileged: true
        args:
        - -d
        - --web
        - --web.address=:8580
        - --kubernetes
