---
# author: lework

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: install.yml
- include_tasks: configure.yml
- include_tasks: cluster.yml
  when: rabbitmq_cluster

- include_tasks: setup.yml 
