---
# author: lework

- name: configure | Setup nginx.conf.
  template:
    dest: "{{ tengine_conf_file }}"
    src: nginx.conf.j2
    mode: 0644
    owner: "{{ tengine_user }}"
    group: "{{ tengine_group }}"
  notify: restart tengine

- name: configure | Setup nginx_vhosts_conf.conf.
  template:
    dest: "{{ tengine_conf_path }}/conf.d/{{ item.server_name | d('default') }}.conf"
    src: nginx_vhosts_conf.j2
    mode: 0644
    owner: "{{ tengine_user }}"
    group: "{{ tengine_group }}"
  with_items: "{{ tengine_vhosts }}"
  when: tengine_vhosts | length > 0
  notify: restart tengine

- name: configure | Setup nginx_vhosts_conf.conf.
  template:
    dest: "{{ tengine_conf_path }}/conf.d/00_upstreams.conf"
    src: nginx_upstreams_conf.j2
    mode: 0644
    owner: "{{ tengine_user }}"
    group: "{{ tengine_group }}"
  when: tengine_upstreams | length > 0
  notify: restart tengine

- name: configure | Setup default.conf.
  template:
    dest: "{{ tengine_conf_path }}/conf.d/default.conf"
    src: nginx_default_server_conf.j2
    mode: 0644
    owner: "{{ tengine_user }}"
    group: "{{ tengine_group }}"
  when: not tengine_upstreams and not tengine_proxys and not tengine_vhosts
  notify: restart tengine
  
