---
# author: lework

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: install.yml
- include: configure.yml 
- include: logrotate.yml
- include: service.yml
