---
# author: lework

- name: logrotate | Setup Tomcat logrotate conf file.
  template:
    dest: "{{ tomcat_work_path }}/conf/logrotate.conf"
    src: tomcat.logrotate.j2

- name: logrotate | Create a cron rule.
  cron:
    name: "Logrotate {{ tomcat_services_name }} catalina-daemon.out"
    minute: "59"
    hour: "23"
    job: "sleep 57;/usr/sbin/logrotate -vf {{ tomcat_work_path }}/conf/logrotate.conf >> /var/log/logrotate-{{ tomcat_services_name }}.log 2>&1"