---
# author: lework

- block:
  - name: setup_binary | Check if openjdk local file is already configured.
    stat: path={{ openjdk_binary_file_path }}
    register: openjdk_file_result
  
  - name: setup_binary | Confirm the existence of the software directory.
    file: path={{ software_files_path }} state=directory
    when: not openjdk_file_result.stat.exists
    
  - name: setup_binary | Download openjdk file.
    get_url: url={{ openjdk_binary_file_url }} dest={{ software_files_path }}
    when: not openjdk_file_result.stat.exists
  connection: local
  run_once: yes

- name: setup_binary | Confirm the existence of the installation directory.
  file: path={{ software_install_path }} state=directory

- name: setup_binary | Copy openjdk file to agent.
  unarchive:
    src: "{{ openjdk_binary_file_path }}"
    dest: "{{ software_install_path }}"
    creates: "{{ java_home }}"
  
- name: setup_binary | Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home != ""
