---
# author: lework

- name: setup_package | Include version-specific variables for CentOS/RHEL.
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux' or
        ansible_distribution == 'RedHat'

- name: setup_package | Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: setup_package | Include version-specific variables for Debian.
  include_vars: "{{ ansible_distribution|title }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: setup_package | Define openjdk_packages.
  set_fact:
    openjdk_packages: "{{ __openjdk_packages | list }}"
  when: openjdk_packages is not defined

- name: setup_package | Update apt cache.
  apt: update_cache=true cache_valid_time=600
  when: ansible_os_family == 'Debian'
  changed_when: false

- name: setup_package | Ensure Java is installed.
  package:
    name: "{{ openjdk_packages }}"
    state: present
