---
# author: lework

- name: backup | 创建存储备份的目录。
  file: path={{ deploy_code_history_path }}/{{ ansible_date_time.date }}/ state=directory

- name: backup | 备份上线的代码。
  shell: "mv {{ deploy_code_online_path }}/{{ deploy_file_stats.stdout_lines[0] | basename }} {{ deploy_code_history_path }}/{{ ansible_date_time.date }}/{{ deploy_file_stats.stdout_lines[0] | basename }}-{{ ansible_date_time.epoch }}"
