---
# author: lework

- name: check | 发布文件是否存在。
  shell: "ls {{ deploy_file }}"
  connection: local
  become: no
  register: deploy_file_stats
  changed_when: false
  failed_when: deploy_file_stats.stdout_lines[0] == "" or deploy_file == ""

- name: check | 服务家目录如果不存在则创建。
  file: path={{ deploy_service_workpath }} owner={{ deploy_service_user }} state=directory
  
- name: check | 检查supervisorctl状态。
  shell: "{{ deploy_service_start_script }} status"
  changed_when: false

- name : check | 清空代码更新的目录
  file: path="{{ deploy_code_online_path | d('/tmp/letest') }}/{{ deploy_file_stats.stdout_lines[0] | basename }} state=absent"
  
- name: check | 代码存储目录如果不存在则创建。
  file: path={{ item }} state=directory
  with_items:
   - "{{ deploy_code_online_path }}"
   - "{{ deploy_code_previous_path }}"
   - "{{ deploy_code_history_path }}"
