apiVersion: v1
kind: Endpoints
metadata:
  namespace: kube-system
  name: kube-controller-manager-prometheus-discovery
  labels:
    k8s-app: kube-controller-manager
subsets:
- addresses:
{% for ip in groups['k8s_master'] %} 
  - ip: {{ ip }}
{% endfor %}
  ports:
  - name: http-metrics
    port: 10252
    protocol: TCP
