apiVersion: v1
kind: Endpoints
metadata:
  namespace: kube-system
  name: kube-scheduler-prometheus-discovery
  labels:
    k8s-app: kube-scheduler
subsets:
- addresses:
{% for ip in groups['k8s_master'] %}
  - ip: {{ ip }}
{% endfor %}
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP
