---
# author: lework

software_install_path: '/usr/local'
kubernetes_bin_path: '{{ software_install_path }}/kubernetes/bin'
kubernetes_cni_bin_path: '{{ software_install_path }}/cni/bin'
kubernetes_cfssl_bin_path: '{{ software_install_path }}/cfssl/bin'
kubernetes_helm_bin_path: '{{ software_install_path }}/helm/bin'
kubernetes_calic_bin_path: '{{ software_install_path }}/calic/bin'

kubernetes_node_packages:
  - socat
  - openssl
  - curl

kubernetes_min_ram: 3600

kubernetes_tmp_path: "/tmp/ansibe.fetch"
kubernetes_etcd_conf_path: '/etc/etcd'
kubernetes_etcd_ssl_path: '{{ kubernetes_etcd_conf_path }}/ssl'
kubernetes_etcd_data_path: "/var/lib/etcd"

kubernetes_cni_conf_path: "/etc/cni/net.d"
kubernetes_haproxy_conf_path: "/etc/haproxy"
kubernetes_images_path: "/opt/software/kubernetes/images"

kubernetes_log_path: "/var/log/kubernetes"
kubernetes_conf_path: "/etc/kubernetes"
kubernetes_addons_conf_path: "{{ kubernetes_conf_path }}/addons"
kubernetes_pki_path: "{{ kubernetes_conf_path }}/pki"
kubernetes_manifests_path: "{{ kubernetes_conf_path }}/manifests"
kubernetes_kubelet_service_path: "/etc/systemd/system/kubelet.service.d"
kubernetes_kubelet_data_path: "/var/lib/kubelet"

kubernetes_apiserver_vip: ""
kubernetes_apiserver_port: "6443"
kubernetes_cluster_ip: "10.96.0.1"
kubernetes_cluster_dns: "10.96.0.10"
kubernetes_cluster_domain: "cluster.local"
kubernetes_cluster_ip_rang: "10.96.0.0/12"
kubernetes_cluster_cidr: "10.244.0.0/16"

kubernetes_dashboard_port: "443"

kubernetes_haproxy_status_port: "9090"
kubernetes_haproxy_admin_passwd: "admin123"

# Kubernetes ingress: nginx,traefik
kubernetes_ingress_controller: "nginx"

# Kubernetes master
kubernetes_apiserver_image: "gcr.io/google_containers/kube-apiserver-amd64:v1.10.3"
kubernetes_controller_image: "gcr.io/google_containers/kube-controller-manager-amd64:v1.10.3"
kubernetes_scheduler_image:  "gcr.io/google_containers/kube-scheduler-amd64:v1.10.3"
kubernetes_etcd_image: "gcr.io/google_containers/etcd-amd64:3.1.13"
kubernetes_keepalived_image: "lework/keepalived:v1.3.9"
kubernetes_haproxy_image: "haproxy:1.8.9-alpine"

# Kube-proxy
kubernetes_kube_proxy_image: "gcr.io/google_containers/kube-proxy-amd64:v1.10.3"

# kubernetes dashboard
kubernetes_dashboard_image: "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.3"

# Kubernetes network
kubernetes_calico_node_image: "quay.io/calico/node:v3.1.2"
kubernetes_calico_cni_image: "quay.io/calico/cni:v2.0.5"
kubernetes_calico_kube_controllers_image: "quay.io/calico/kube-controllers:v2.0.4"

# Ingress controller
kubernetes_nginx_ingress_controller_image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0"
kubernetes_default_http_backend_image: "gcr.io/google_containers/defaultbackend:1.4"
kubernetes_traefik_ingress_controller_image: "traefik:v1.6.2-alpine"

# Kube-dns
kubernetes_kube_dns_image: "gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.10"
kubernetes_kube_dns_dnsmasq_image: "gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.10"
kubernetes_kube_dns_sidecar_image: "gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.10"

# Kubernetes monitor
kubernetes_heapster_image: "gcr.io/google_containers/heapster-amd64:v1.5.3"
kubernetes_heapster_addon_resizer_image: "gcr.io/google_containers/addon-resizer:1.8.1"
kubernetes_heapster_influxdb_image: "gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3"
kubernetes_heapster_grafana_image: "gcr.io/google_containers/heapster-grafana-amd64:v4.4.3"

# Kubernetes logging
kubernetes_alpine_image: "alpine:3.7"
kubernetes_elasticsearch_image: "gcr.io/google-containers/elasticsearch:v6.2.4"
kubernetes_fluentd_image: "gcr.io/google-containers/fluentd-elasticsearch:v2.1.0"
kubernetes_kibana_image: "docker.elastic.co/kibana/kibana-oss:6.2.4"

kubernetes_logging: true
kubernetes_monitor: true

kubernetes_master: false
kubernetes_node: false
kubernetes_addons: false
kubernetes_ntpd: true
kubernetes_node_init: true
