---
# author: lework

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  
- name: Install dependent package.
  package: name={{ __package }}
  when: __package | length > 0
 
- import_tasks: install_repo.yml
  when: elasticsearch_repo_install | bool
- import_tasks: install_package.yml
  when:
    - not (elasticsearch_repo_install | bool)
    - __package_file is defined and __package_file != ""

- import_tasks: plugin.yml
  when: elasticsearch_plugin | length > 0) or (elasticsearch_plugin_file | length > 0

- import_tasks: ssl.yml
  when: elasticsearch_enable_http_ssl | bool or elasticsearch_enable_transport_ssl | bool

- import_tasks: configure.yml
