apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: external-dns
data:
  Corefile: |-
    .:53 {
      log . {
        class denial
      }
      cache
      errors
      loadbalance round_robin
      whoami
      health
      prometheus 0.0.0.0:9153
      forward . 223.5.5.5:53
    }

    k8s.local {
      etcd k8s.local {
        stubzones
        path /skydns
        endpoint http://coredns-etcd:2379
        upstream 223.5.5.5:53 223.6.6.6:53
        debug
      }
      errors
      log
    }
