---
# author: lework


- name: plugins | Wait for jenkins http port is LISTEN.
  wait_for: port={{ jenkins_http_port }} delay=5

- name: plugins | Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  register: __reg_jarfile_get
  until: "'OK' in __reg_jarfile_get.msg or 'file already exists' in __reg_jarfile_get.msg"
  retries: 10
  delay: 5
  check_mode: no
    
- name: plugins | Install Jenkins plugins using password.
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
    -auth {{ jenkins_admin_username }}:{{ jenkins_admin_password }}
    install-plugin {{ item }}
    creates="{{ jenkins_home }}/plugins/{{ item }}.jpi"
  register: install_plugins
  until: install_plugins.rc == 0
  retries: 5
  delay: 5
  with_items: 
    - "{{ jenkins_plugins_recommended }}"
    - "{{ jenkins_plugins_extra }}"
  when: jenkins_admin_password != ""
  notify: restart jenkins
