---
# author: lework


# Variable setup.
- name: Include OS-Specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  
# install tasks.
- include_tasks: 1.install.yml

# Configure Jenkins init configure.
- include_tasks: 2.configure.yml

# Update Jenkins and install configured plugins.
- include_tasks: 3.plugins.yml

# Clear temporary files.
- include_tasks: 4.clear.yml