---
# author: lework

- name: env | bashrc.
  blockinfile:
    path: "{{ __bashrc_file }}"
    backup: yes
    create: yes
    marker: "# ansible os-init {mark}"
    block: |
      # history actions record，include action time, user, login ip
      HISTFILESIZE=4000
      HISTSIZE=4000
      USER_IP=`who -u am i 2>/dev/null| awk '{print $NF}'|sed -e 's/[()]//g'`
      if [ -z $USER_IP ]
      then
        USER_IP=`hostname`
      fi
      HISTTIMEFORMAT="%F %T $USER_IP:`whoami` "
      export HISTTIMEFORMAT
      # aliases
      alias ll="ls -cal --time-style '+%Y-%m-%d %H:%M:%S'"
  tags:
   - bashrc
